---
# Source: stakater-push-main-tag-bitbucket/templates/task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: stakater-push-main-tag-bitbucket
  labels:
    app.kubernetes.io/version: "0.0.0"
spec:
  params:
    - name: SEM_VER
      type: string
      description: The new version to push
    - name: PR_NUMBER
      type: string
      default: NA
      description: >-
        In case of PR, PR number that is to be used in image tag. If this field
        is empty it means that it's a commit on main branch
    - name: GIT_REVISION
      type: string
      description: The git revision
    - name: BITBUCKET_TOKEN
      type: string
      default: "git-auth"
      description: Secret that stores the Access Token and User Email for BitBucket
    - name: REPO_URL
      type: string
      description: URL of the repository.
    - name: CUSTOM_CA_CERT_PATH
      type: string
      default: ""
  steps:
    - args:
        - '-c'
        - >
          set -e


          pwd;


          REPO_PATH=$(params.REPO_URL)

          if [[ $(params.REPO_URL) == https://* ]]; then
            REPO_PATH=${REPO_PATH#"https://"}
          fi

          if [[ $(params.REPO_URL) == http://* ]]; then
            REPO_PATH=${REPO_PATH#"http://"}
          fi

          sleep 1000;

          if [ $(params.PR_NUMBER) == "NA" ] && \
           ( [ $(params.GIT_REVISION) == "main" ] || [ $(params.GIT_REVISION) == "master" ] ); then
          
          if [[ $(params.CUSTOM_CA_CERT_PATH) != "" ]]; then
            git config http.sslCAInfo $(params.CUSTOM_CA_CERT_PATH)
          fi

          git remote set-url origin "https://${GIT_USERNAME}:${ACCESS_TOKEN}@${REPO_PATH}"

          git config user.email ${GIT_EMAIL}
        

          git tag -am "Bump version to $(params.SEM_VER)" $(params.SEM_VER)
          
          git push --tags
          
          fi
          
      command:
        - /bin/bash
      image: 'stakater/pipeline-toolbox:v0.0.36'
      name: push-main-tag
      resources: {}
      workingDir: $(workspaces.source.path)
      env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.BITBUCKET_TOKEN)
              key: username
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.BITBUCKET_TOKEN)
              key: token
        - name: GIT_EMAIL
          valueFrom:
            secretKeyRef:
              name: $(params.BITBUCKET_TOKEN)
              key: email
  workspaces:
    - name: source
